// SCORM bundle preview — single-row card with the bundle metadata. Schema:
// { url, filename, size_bytes, built_at }. The bundle is generated by a
// separate exporter; this just shows the latest build.

interface ScormPayload {
  url: string;
  filename: string;
  size_bytes: number;
  built_at: string;
}

export function PreviewSCORM({ payload }: { payload: Record<string, unknown> | null }) {
  if (!payload || !payload.url) {
    return (
      <div className="text-center py-12 text-sm text-slate-500">
        No SCORM bundle built yet.<br />
        <span className="text-xs text-slate-400">Approve the other artifacts first, then build a bundle.</span>
      </div>
    );
  }
  const p = payload as unknown as ScormPayload;

  return (
    <div className="rounded-lg border border-slate-200 p-4 flex items-center gap-4">
      <div className="text-3xl">📦</div>
      <div className="flex-1 min-w-0">
        <div className="font-semibold text-slate-900 truncate">{p.filename}</div>
        <div className="text-xs text-slate-500 mt-0.5">
          {(p.size_bytes / 1024).toFixed(0)} KB · built {new Date(p.built_at).toLocaleString()}
        </div>
      </div>
      <a
        href={p.url}
        target="_blank"
        rel="noreferrer"
        className="px-3 py-1.5 text-sm font-semibold text-white bg-bi-navy-700 hover:bg-bi-navy-800 rounded-md"
      >
        Download .zip
      </a>
    </div>
  );
}
